### ISSUE TITLE
Deploy via Intune

### ISSUE THREAD

**Issue by StuartK73** [LesFerch/LaunchIE#2]
Hi Buddy

I hope you are well.

Anyway, is there any way to deploy your LaunchIE or IEModeExpiryFix via Intune?

Info greatly appreciated.

Stuart

**Comment by LesFerch** [comment]
You could make a tiny wrapper script that copies it to the folder of your choice, as discussed here:
https://www.reddit.com/r/Intune/comments/186vixm/deploying_portable_apps_with_intune/

But if your computers are in Active Directory, couldn't you use [Enterprise Mode and the Enterprise Mode Site List](https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/what-is-enterprise-mode) instead of LaunchIE or IEModeExpiryFix?

**Comment by StuartK73** [comment]
Hi Buddy

Many thanks for taking the time to reply, much appreciated.

Our Windows devices are Azure AD / Entra ID Joined only, no AD.

I'll see if I can figure out deploying IELaunch.exe.

I think the IEModeExpiryFix might be a good fit for us, would you know how to deploy the PowerShell version?

Info appreciated.

Stuart

**Comment by LesFerch** [comment]
Do you have any system in place to run scripts for each user, either at every login or once per user?

**Comment by StuartK73** [comment]
Intune should be able to do that I think.

Stuart
